services:
  - type: redis
    name: redis
    ipAllowList: []

  - type: web
    name: web
    env: docker
    plan: free
    dockerfilePath: ./app/Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host
      - key: PORT
        value: 5000

  - type: web
    name: proxy
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.proxy
