events { worker_connections 1024; }

http {
    server {
        listen 80;

        location / {
            proxy_pass http://web-hkjg.onrender.com;
            proxy_set_header Host web-hkjg.onrender.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_server_name on;
        }
    }
}
